// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: protobuf/currency/exchange_rate_service.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protobuf_currency_exchange_rate_service_proto protoreflect.FileDescriptor

const file_protobuf_currency_exchange_rate_service_proto_rawDesc = "" +
	"\n" +
	"-protobuf/currency/exchange_rate_service.proto\x12\bcurrency\x1a-protobuf/currency/exchange_rate_request.proto\x1a.protobuf/currency/exchange_rate_response.proto2g\n" +
	"\x13ExchangeRateService\x12P\n" +
	"\x0fGetExchangeRate\x12\x1d.currency.ExchangeRateRequest\x1a\x1e.currency.ExchangeRateResponseB?Z=github.com/ivan-prykhodko/envoy-workshop/protogen/go/currencyb\x06proto3"

var file_protobuf_currency_exchange_rate_service_proto_goTypes = []any{
	(*ExchangeRateRequest)(nil),  // 0: currency.ExchangeRateRequest
	(*ExchangeRateResponse)(nil), // 1: currency.ExchangeRateResponse
}
var file_protobuf_currency_exchange_rate_service_proto_depIdxs = []int32{
	0, // 0: currency.ExchangeRateService.GetExchangeRate:input_type -> currency.ExchangeRateRequest
	1, // 1: currency.ExchangeRateService.GetExchangeRate:output_type -> currency.ExchangeRateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_currency_exchange_rate_service_proto_init() }
func file_protobuf_currency_exchange_rate_service_proto_init() {
	if File_protobuf_currency_exchange_rate_service_proto != nil {
		return
	}
	file_protobuf_currency_exchange_rate_request_proto_init()
	file_protobuf_currency_exchange_rate_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_currency_exchange_rate_service_proto_rawDesc), len(file_protobuf_currency_exchange_rate_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_currency_exchange_rate_service_proto_goTypes,
		DependencyIndexes: file_protobuf_currency_exchange_rate_service_proto_depIdxs,
	}.Build()
	File_protobuf_currency_exchange_rate_service_proto = out.File
	file_protobuf_currency_exchange_rate_service_proto_goTypes = nil
	file_protobuf_currency_exchange_rate_service_proto_depIdxs = nil
}
