// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: protobuf/currency/exchange_rate_request.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateRequest) Reset() {
	*x = ExchangeRateRequest{}
	mi := &file_protobuf_currency_exchange_rate_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateRequest) ProtoMessage() {}

func (x *ExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_currency_exchange_rate_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_currency_exchange_rate_request_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

var File_protobuf_currency_exchange_rate_request_proto protoreflect.FileDescriptor

const file_protobuf_currency_exchange_rate_request_proto_rawDesc = "" +
	"\n" +
	"-protobuf/currency/exchange_rate_request.proto\x12\bcurrency\"[\n" +
	"\x13ExchangeRateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrencyB?Z=github.com/ivan-prykhodko/envoy-workshop/protogen/go/currencyb\x06proto3"

var (
	file_protobuf_currency_exchange_rate_request_proto_rawDescOnce sync.Once
	file_protobuf_currency_exchange_rate_request_proto_rawDescData []byte
)

func file_protobuf_currency_exchange_rate_request_proto_rawDescGZIP() []byte {
	file_protobuf_currency_exchange_rate_request_proto_rawDescOnce.Do(func() {
		file_protobuf_currency_exchange_rate_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_currency_exchange_rate_request_proto_rawDesc), len(file_protobuf_currency_exchange_rate_request_proto_rawDesc)))
	})
	return file_protobuf_currency_exchange_rate_request_proto_rawDescData
}

var file_protobuf_currency_exchange_rate_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_currency_exchange_rate_request_proto_goTypes = []any{
	(*ExchangeRateRequest)(nil), // 0: currency.ExchangeRateRequest
}
var file_protobuf_currency_exchange_rate_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_currency_exchange_rate_request_proto_init() }
func file_protobuf_currency_exchange_rate_request_proto_init() {
	if File_protobuf_currency_exchange_rate_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_currency_exchange_rate_request_proto_rawDesc), len(file_protobuf_currency_exchange_rate_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_currency_exchange_rate_request_proto_goTypes,
		DependencyIndexes: file_protobuf_currency_exchange_rate_request_proto_depIdxs,
		MessageInfos:      file_protobuf_currency_exchange_rate_request_proto_msgTypes,
	}.Build()
	File_protobuf_currency_exchange_rate_request_proto = out.File
	file_protobuf_currency_exchange_rate_request_proto_goTypes = nil
	file_protobuf_currency_exchange_rate_request_proto_depIdxs = nil
}
