// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: protobuf/currency/exchange_rate_response.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeRate  *ExchangeRate          `protobuf:"bytes,1,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_protobuf_currency_exchange_rate_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_currency_exchange_rate_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_currency_exchange_rate_response_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRateResponse) GetExchangeRate() *ExchangeRate {
	if x != nil {
		return x.ExchangeRate
	}
	return nil
}

var File_protobuf_currency_exchange_rate_response_proto protoreflect.FileDescriptor

const file_protobuf_currency_exchange_rate_response_proto_rawDesc = "" +
	"\n" +
	".protobuf/currency/exchange_rate_response.proto\x12\bcurrency\x1a%protobuf/currency/exchange_rate.proto\"S\n" +
	"\x14ExchangeRateResponse\x12;\n" +
	"\rexchange_rate\x18\x01 \x01(\v2\x16.currency.ExchangeRateR\fexchangeRateB?Z=github.com/ivan-prykhodko/envoy-workshop/protogen/go/currencyb\x06proto3"

var (
	file_protobuf_currency_exchange_rate_response_proto_rawDescOnce sync.Once
	file_protobuf_currency_exchange_rate_response_proto_rawDescData []byte
)

func file_protobuf_currency_exchange_rate_response_proto_rawDescGZIP() []byte {
	file_protobuf_currency_exchange_rate_response_proto_rawDescOnce.Do(func() {
		file_protobuf_currency_exchange_rate_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_currency_exchange_rate_response_proto_rawDesc), len(file_protobuf_currency_exchange_rate_response_proto_rawDesc)))
	})
	return file_protobuf_currency_exchange_rate_response_proto_rawDescData
}

var file_protobuf_currency_exchange_rate_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_currency_exchange_rate_response_proto_goTypes = []any{
	(*ExchangeRateResponse)(nil), // 0: currency.ExchangeRateResponse
	(*ExchangeRate)(nil),         // 1: currency.ExchangeRate
}
var file_protobuf_currency_exchange_rate_response_proto_depIdxs = []int32{
	1, // 0: currency.ExchangeRateResponse.exchange_rate:type_name -> currency.ExchangeRate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_currency_exchange_rate_response_proto_init() }
func file_protobuf_currency_exchange_rate_response_proto_init() {
	if File_protobuf_currency_exchange_rate_response_proto != nil {
		return
	}
	file_protobuf_currency_exchange_rate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_currency_exchange_rate_response_proto_rawDesc), len(file_protobuf_currency_exchange_rate_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_currency_exchange_rate_response_proto_goTypes,
		DependencyIndexes: file_protobuf_currency_exchange_rate_response_proto_depIdxs,
		MessageInfos:      file_protobuf_currency_exchange_rate_response_proto_msgTypes,
	}.Build()
	File_protobuf_currency_exchange_rate_response_proto = out.File
	file_protobuf_currency_exchange_rate_response_proto_goTypes = nil
	file_protobuf_currency_exchange_rate_response_proto_depIdxs = nil
}
